# Câu 1: python hỗ trợ những kiểu dễ liệu nào?

"""
Python hỗ trợ các kiểu dữ liệu cơ bản sau:

1. int (số nguyên): Ví dụ: 1,2,3,...
2. float (số thực): Ví dụ: 1.0, 2.5, 5.14,...
3. str (chuỗi ký tự): Ví dụ: "hello", "world",...
4. bool (Boolean): True, False
5. list (danh sách): [1,2,3], ['apple', 'banana', 'cherry'],...
6. tuple (bộ giá trị): (1,2,3), ('apple', 'banana', 'cherry'),...
7. dict (từ điển): {"name": "John", "age": 30},...
8. set (tập hợp): {1,2,3}, {"apple", "banana", "cherry"},...
"""
